# https://github.com/alacritty/alacritty/issues/2956#issuecomment-549505530
shell:
  program: /bin/bash
  args:
  - -l
  - -c
  - tmux attach || tmux

font:
  normal:
    family: FiraCode Nerd Font
    style: Regular

  bold:
    family: FiraCode Nerd Font
    style: Bold

  italic:
    family: FiraCode Nerd Font
    style: Italic

  bold_italic:
    family: FiraCode Nerd Font
    style: Bold Italic

  size: 12.0
