# https://yazi-rs.github.io/docs/configuration/overview/
# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml
[mgr]
show_hidden = true
show_symlink = true
sort_by = "natural"
