# https://yazi-rs.github.io/docs/configuration/overview/
# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml
[mgr]
show_hidden = true
show_symlink = true
sort_by = "natural"

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[plugin]
prepend_previewers = [
    # Archive previewer
    { mime = "application/*zip", run = "ouch" },
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/x-bzip2", run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar", run = "ouch" },
    { mime = "application/vnd.rar", run = "ouch" },
    { mime = "application/x-xz", run = "ouch" },
    { mime = "application/xz", run = "ouch" },
    { mime = "application/x-zstd", run = "ouch" },
    { mime = "application/zstd", run = "ouch" },
    { mime = "application/java-archive", run = "ouch" },
]
